### ISSUE TITLE
Hi! How are the Feature vectors converted to raw label predictions？

### ISSUE THREAD

**Issue by wangchichi1999** [XunGuangxu/CorNet#3]
![0`V1`S$ WD@LSD(SU731ML8](https://user-images.githubusercontent.com/62172616/113123202-f1618c00-9246-11eb-9cd6-16a41b53d1f4.png)
In CorNetBERTXML model, are Feature vectors converted to raw label predictions by sigmoid activation function?

**Comment by XunGuangxu** [comment]
Hi, the feature vector is converted to the label vector using a fully connected layer. If you want the label values between 0 and 1, you can add a sigmoid afterwards (in my code, I used the BCEWithLogitsLoss. So no need for sigmoid in training).
